[project]
name = "ml_dtypes"
description = ""
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [{name = "ml_dtypes authors", email="ml_dtypes@google.com"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Science/Research",
]
keywords = []

# pip dependencies of the project
dependencies = []

# This is set automatically by flit using `ml_dtypes.__version__`
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/jax-ml/ml_dtypes"
repository = "https://github.com/jax-ml/ml_dtypes"
# Other: `documentation`, `changelog`

[project.optional-dependencies]
# Development deps (unittest, linting, formating,...)
# Installed through `pip install .[dev]`
dev = [
    "pytest",
    "pytest-xdist",
    "pylint>=2.6.0",
    "pyink",
]

[tool.pyink]
# Formatting configuration to follow Google style-guide
pyink-indentation = 2
pyink-use-majority-quotes = true

[build-system]
requires = ["setuptools>=61", "numpy~=1.21", "pybind11>=2.10.3"]
build-backend = "setuptools.build_meta"

[tools.setuptools]
packages = ["ml_dtypes"]

[tool.setuptools.packages]
find = {}
